export const REQUEST_PROJECTS = 'REQUEST_PROJECTS';
export const RECEIVE_PROJECTS = 'RECEIVE_PROJECTS';


export const REQUEST_CREATE_PROJECTS = 'REQUEST_CREATE_PROJECTS';
export const RECEIVE_CREATE_PROJECTS = 'RECEIVE_CREATE_PROJECTS';
