export const REQUEST_BANNER = "REQUEST_BANNER";
export const RECEIVE_BANNER = "RECEIVE_BANNER";

export const REQUEST_EDITAR = "REQUEST_EDITAR";
export const RECEIVE_EDITAR = "RECEIVE_EDITAR";

export const REQUEST_DELETE = "REQUEST_DELETE";
export const RECEIVE_DELETE = "RECEIVE_DELETE";

export const ALERT_SUCCESS = 'ALERT_SUCCESS';

export const REQUEST_ADDBANNER = "REQUEST_ADDBANNER";
export const RECEIVE_ADDBANNER = "RECEIVE_ADDBANNER";

export const ACTIVE_MODAL = "ACTIVE_MODAL";

export const REQUEST_ISACTIVE_BANNER = "REQUEST_ISACTIVE_BANNER";
export const RECEIVE_ISACTIVE_BANNER = "RECEIVE_ISACTIVE_BANNER";
